# Generated by Django 2.0.4 on 2018-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdExcel',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('stdfile', models.FileField(upload_to='static/stdfiles/', verbose_name='学生excel文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传文件时间')),
            ],
        ),
    ]
